# Decision Tree Regressor Implementation

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
## Load the California Housing Dataset
from sklearn.datasets import fetch_california_housing
california_df=fetch_california_housing()

In [3]:
print(california_df.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

In [4]:
california_df.data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [5]:
california_df.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [6]:
## Split into Independent and dependent features
X=pd.DataFrame(data=california_df.data,columns=california_df.feature_names)
y=california_df.target

In [7]:
X.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [8]:
## Train test split the data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [9]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((13828, 8), (13828,), (6812, 8), (6812,))

In [10]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor()

In [11]:
regressor.fit(X_train,y_train)

DecisionTreeRegressor()

In [12]:
y_pred=regressor.predict(X_test)

In [13]:
y_pred

array([0.565  , 0.661  , 5.00001, ..., 1.33   , 1.405  , 5.00001])

In [14]:
from sklearn.metrics import r2_score
score = r2_score(y_pred,y_test)

In [15]:
score

0.5930139699920474

In [16]:
## Hyper Parameter Tuning
parameters ={
            'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
            'splitter':['best','random'],
            'max_depth':[1,2,3,4,5,6,7,8,9,10,11,12],
            'max_features':['auto','sqrt','log2']
}

In [17]:
regressor=DecisionTreeRegressor()

In [18]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import GridSearchCV
regressorcv=GridSearchCV(regressor,param_grid=parameters,cv=5,scoring='neg_mean_squared_error')

In [ ]:
regressorcv.fit(X_train,y_train)

In [ ]:
regressorcv.best_params_